/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_iQdl5AVrA',
  aws_user_pools_web_client_id: '1f7o6o4vhhhnqjbb7homalqmvr',
  oauth: {},
};

export default awsmobile;
