name: Deploy Firebase Functions
on:
  release:
    types: [published, edited]
      
defaults:
  run:
    working-directory: functions
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy 
        env:
          PROJECT_PATH: ./functions
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
