name: Build docker image and publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Build
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./simplq
        file: .Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplq-frontend:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
